#!/bin/bash

# Get PWD
START_PWD=$(pwd)

# Install dependencies
apt update
apt install -y git make build-essential liblzma-dev gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu

# Clone upstream
rm -rf upstream
mkdir -p upstream
git clone https://github.com/ipxe/ipxe.git upstream

# Checkout latest release
cd upstream
git checkout $(git describe --tags $(git rev-list --tags --max-count=1))

# Enable Protocols
sed -i -e 's/#undef\tDOWNLOAD_PROTO_HTTPS/#define\tDOWNLOAD_PROTO_HTTPS/g' src/config/general.h
sed -i -e 's/#undef\tDOWNLOAD_PROTO_FTP/#define\tDOWNLOAD_PROTO_FTP/g' src/config/general.h
sed -i -e 's/#undef\tDOWNLOAD_PROTO_SLAM/#define\tDOWNLOAD_PROTO_SLAM/g' src/config/general.h
sed -i -e 's/#undef\tDOWNLOAD_PROTO_NFS/#define\tDOWNLOAD_PROTO_NFS/g' src/config/general.h

# Enable Commmands
sed -i -e 's|//#define NSLOOKUP_CMD|#define NSLOOKUP_CMD|g' src/config/general.h
sed -i -e 's|//#define TIME_CMD|#define TIME_CMD|g' src/config/general.h
sed -i -e 's|//#define DIGEST_CMD|#define DIGEST_CMD|g' src/config/general.h
sed -i -e 's|//#define LOTEST_CMD|#define LOTEST_CMD|g' src/config/general.h
sed -i -e 's|//#define VLAN_CMD|#define VLAN_CMD|g' src/config/general.h
sed -i -e 's|//#define PXE_CMD|#define PXE_CMD|g' src/config/general.h
sed -i -e 's|//#define REBOOT_CMD|#define REBOOT_CMD|g' src/config/general.h
sed -i -e 's|//#define POWEROFF_CMD|#define POWEROFF_CMD|g' src/config/general.h
sed -i -e 's|//#define IMAGE_TRUST_CMD|#define IMAGE_TRUST_CMD|g' src/config/general.h
sed -i -e 's|//#define PCI_CMD|#define PCI_CMD|g' src/config/general.h
sed -i -e 's|//#define PARAM_CMD|#define PARAM_CMD|g' src/config/general.h
sed -i -e 's|//#define NEIGHBOUR_CMD|#define NEIGHBOUR_CMD|g' src/config/general.h
sed -i -e 's|//#define PING_CMD|#define PING_CMD|g' src/config/general.h
sed -i -e 's|//#define CONSOLE_CMD|#define CONSOLE_CMD|g' src/config/general.h
sed -i -e 's|//#define IPSTAT_CMD|#define IPSTAT_CMD|g' src/config/general.h
sed -i -e 's|//#define PROFSTAT_CMD|#define PROFSTAT_CMD|g' src/config/general.h
sed -i -e 's|//#define NTP_CMD|#define NTP_CMD|g' src/config/general.h
sed -i -e 's|//#define CERT_CMD|#define CERT_CMD|g' src/config/general.h
sed -i -e 's|//#define IMAGE_MEM_CMD|#define IMAGE_MEM_CMD|g' src/config/general.h

# Copy the embedded script
cd src
cp ../../downstream/init.ipxe .

# Add the embedded script and use all cores
shopt -s expand_aliases
alias EMBEDDED_MAKE="make EMBED=\"init.ipxe\" -j$(nproc)"

# Build
EMBEDDED_MAKE bin-i386-pcbios/ipxe.kpxe &                                           # Legacy
EMBEDDED_MAKE bin-i386-efi/ipxe.efi &                                               # UEFI i386
EMBEDDED_MAKE bin-x86_64-efi/ipxe.efi &                                             # UEFI x86_64
EMBEDDED_MAKE CROSS_COMPILE=arm-linux-gnueabi- ARCH=arm32 bin-arm32-efi/snp.efi &   # UEFI arm32
EMBEDDED_MAKE CROSS_COMPILE=aarch64-linux-gnu- ARCH=arm64 bin-arm64-efi/snp.efi &   # UEFI arm64

# Wait for builds to complete
wait

# Create tmp directory
rm -rf ../../tmp
mkdir -p ../../tmp

# Stage
cp bin-i386-pcbios/ipxe.kpxe ../../tmp/ipxe-i386.kpxe                               # Legacy
cp bin-i386-efi/ipxe.efi ../../tmp/ipxe-i386.efi                                    # UEFI i386
cp bin-x86_64-efi/ipxe.efi ../../tmp/ipxe-x86_64.efi                                # UEFI x86_64
cp bin-arm32-efi/snp.efi ../../tmp/ipxe-arm32.efi                                   # UEFI arm32
cp bin-arm64-efi/snp.efi ../../tmp/ipxe-arm64.efi                                   # UEFI arm64

# Stage downstream files
cp ../../downstream/*.ipxe ../../tmp/.
rm -rf ../../tmp/init.ipxe

# Create tar archive in staging directory
rm -rf ../../staging
mkdir -p ../../staging
tar -zcvf ../../staging/ipxe.tar.gz -C ../../tmp .

# Go back to starting dir
cd $START_PWD
