name: hydrun CI

on:
  push:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build-linux:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Vars
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT"
          echo "rfc3339=$(date --rfc-3339=seconds | sed 's/ /T/')Z >> $GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up hydrun
        run: |
          curl -L -o /tmp/hydrun "https://github.com/pojntfx/hydrun/releases/latest/download/hydrun.linux-$(uname -m)"
          sudo install /tmp/hydrun /usr/local/bin
      - name: Build with hydrun
        run: hydrun -a amd64 ./Hydrunfile
      - name: Build and Push Dockerfile
        run: docker buildx bake -f ./docker-bake.hcl --push --provenance=false
        env:
          REPO: ${{ github.repository }}
          TAG: latest
          CREATED: ${{ steps.vars.outputs.rfc3339 }}
          DESCRIPTION: iPXE tftp server
          URL: https://github.com/${{ github.repository }}
          SHA: ${{ github.sha }}
          AUTHOR: ${{ github.repository_owner }}
      - name: Publish to GitHub releases
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            tmp/*
            staging/*
