name: hydrun CI

on:
  push:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build-linux:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Vars
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT"
          echo "rfc3339=$(date --rfc-3339=seconds | sed 's/ /T/')Z >> $GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up hydrun
        run: |
          curl -L -o /tmp/hydrun "https://github.com/pojntfx/hydrun/releases/latest/download/hydrun.linux-$(uname -m)"
          sudo install /tmp/hydrun /usr/local/bin
      - name: Build with hydrun
        run: hydrun -a amd64 ./Hydrunfile
      - name: List built files
        run: ls -la tmp
      - name: Publish to GitHub releases
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            tmp/*
            staging/*
      - name: Build and Push Dockerfile
        id: docker_build
        uses: docker/build-push-action@v4.0.0
        with:
          platforms: linux/arm64,linux/armhf,linux/arm/v7,linux/386,linux/amd64
          version: 0.7.0
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.artifact.created:${{ steps.vars.outputs.rfc3339 }}
            org.opencontainers.artifact.description:iPXE tftp server
            org.opencontainers.image.created:${{ steps.vars.outputs.rfc3339 }}
            org.opencontainers.image.authors:${AUTHOR}
            org.opencontainers.image.url:https://github.com/${{ github.repository }}
            org.opencontainers.image.source:https://github.com/${{ github.repository }}
            org.opencontainers.image.version:${{ github.sha }}
            org.opencontainers.image.revision:${{ github.sha }}
            org.opencontainers.image.title:iPXE tftp server
            org.opencontainers.image.description:iPXE tftp server built on alpine:latest
            org.opencontainers.image.base.name:docker.io/alpine:latest
          pull: false
          context: .
