name: hydrun CI

on:
  push:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build-linux:
    name: Build
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
      rfc3339: ${{ steps.vars.outputs.rfc3339 }}
      week_of_year: ${{ steps.vars.outputs.week_of_year }}
      ipxe_version: ${{ steps.vars.outputs.ipxe_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up hydrun
        run: |
          curl -L -o /tmp/hydrun "https://github.com/pojntfx/hydrun/releases/latest/download/hydrun.linux-$(uname -m)"
          sudo install /tmp/hydrun /usr/local/bin
      - name: Build with hydrun
        run: hydrun -a amd64 ./Hydrunfile
      - name: Get Vars
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          echo "rfc3339=$(date --rfc-3339=seconds | sed 's/ /T/')Z" >> "$GITHUB_OUTPUT"
          echo "week_of_year=$(date +'%Y%U')" >> "$GITHUB_OUTPUT"
          echo "ipxe_version=$(cd upstream; git describe --tags $(git rev-list --tags --max-count=1))" >> "$GITHUB_OUTPUT"
      - name: Store artifacts
        uses: actions/upload-artifact@master
        with:
          name: tmp-artifacts
          path: container
      - name: Store staging artifacts
        uses: actions/upload-artifact@master
        with:
          name: staging-artifacts
          path: staging

  release:
    name: Publish to github release
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build-linux

    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: staging-artifacts
          path: staging
      - name: Publish to GitHub releases
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "iPXE Build ${{needs.build-linux.outputs.ipxe_version}}"
          automatic_release_tag: ${{needs.build-linux.outputs.week_of_year}}
          prerelease: false
          files: staging/*

  container:
    name: Publish to container
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build-linux

    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: tmp-artifacts
          path: tmp
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download latest netboot.xyz
        run: |
          wget $(curl https://api.github.com/repos/netbootxyz/netboot.xyz/releases/latest | grep "browser_" | grep menus.tar.gz | cut -d '"' -f4) -O menus.tar.gz
          tar -xzvf menus.tar.gz -C ./tmp
          rm -rf ./tmp/boot.cfg
          cp ./downstream/boot.cfg ./tmp/boot.cfg
      - name: Build and Push Dockerfile
        id: docker_build
        uses: docker/build-push-action@v3.2.0
        with:
          platforms: linux/arm64,linux/armhf,linux/386,linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{needs.build-linux.outputs.week_of_year}}
          labels: |
            org.opencontainers.artifact.created:${{needs.build-linux.outputs.rfc3339}}
            org.opencontainers.artifact.description:iPXE tftp server
            org.opencontainers.image.created:${{needs.build-linux.outputs.rfc3339}}
            org.opencontainers.image.authors:${AUTHOR}
            org.opencontainers.image.url:https://github.com/${{ github.repository }}
            org.opencontainers.image.source:https://github.com/${{ github.repository }}
            org.opencontainers.image.version:${{ github.sha }}
            org.opencontainers.image.revision:${{ github.sha }}
            org.opencontainers.image.title:iPXE tftp server
            org.opencontainers.image.description:iPXE tftp server built on alpine:latest with iPXE ${{needs.build-linux.outputs.ipxe_version}}
            org.opencontainers.image.base.name:docker.io/alpine:latest
          pull: false
          context: .
